workflows:
  android-beta-release:
    name: Android Beta test release workflow
    max_build_duration: 60
    scripts:
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
       email:
         recipients:
           - giangerbaldo@gmail.com
         notify:
           success: false
           failure: false